### ISSUE TITLE
第三方在线识别平台无法注册

### ISSUE THREAD

**Issue by Syderny** [Editst/SYSU-HealthReport-Template#4]
快识平台注册的时候一直显示请求失败，不知道有没有遇到同样情况的同学。
我自己找到了另一种验证码识别的方式，使用百度云ai的开放应用，可以解决这个问题：
https://github.com/Syderny/SYSU-HealthReport
https://github.com/Syderny/AutoHealthReport

**Comment by Editst** [comment]
十分感谢，欢迎提pr增加识别方式

**Comment by chensongyu** [comment]
这几天workflow失败应该是因为验证码识别的问题，换成百度云的就ok了

**Comment by Editst** [comment]
换了个自己手糊的 api，效果应该不错
