### ISSUE TITLE
健康申报失败

### ISSUE THREAD

**Issue by ZouJoelin** [Editst/SYSU-HealthReport-Template#7]
这几天不好使了呀？
查workflow发现两天前的log就显示健康申报失败了
![图片](https://user-images.githubusercontent.com/89274834/192744158-b1a6a43f-346d-4111-89be-867b196b0e66.png)

**Comment by Editst** [comment]
我也不确定是什么原因，等有空了再看一下

**Comment by Editst** [comment]
不知道啥原因最近又好了，先关了 issue，有问题再说
